config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  devise_for :users
  
  get 'user/auto_login', to: 'users#auto_login'
 
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :json, :html

  skip_before_action :verify_authenticity_token
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def homepage
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[index show edit update destroy]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def auto_login
    render json: {
      user: current_user
    }
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="/">Instagram</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="/">About</a></li>
        <li class="nav-item"><a class="nav-link" href="/">Services</a></li>
        <li class="nav-item"><a class="nav-link" href="/">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
   <%= link_to 'Booking', root_path, class: 'navbar-brand' %>

   <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %></li>
      </li>
         <li class="nav-item">
        <%= link_to 'edit', edit_user_registration_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
      <li class="nav-item">
        <%= link_to 'sign up', new_user_registration_path, class: "nav-link" %>
      </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bus_booking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_form.html.erb
<h2>Edit</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
     <%= f.input :first_name,
                autofocus: true,
                input_html: { autocomplete: "first_name" }%>
       <%= f.input :last_name,
                autofocus: true,
                input_html: { autocomplete: "last_name" }%>
     <%= f.input :phone_number,
                autofocus: true,
                input_html: { autocomplete: "phone_number" }%>
    <%= f.input :email,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                input_html: { autocomplete: "new-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html..erb
<%= render partial: ",," %>